### PR TITLE
Bump the http crate to 1.0

### PR DESCRIPTION
**Pull request by weiznich**

### CODE REVIEW

**Comment by weiznich** [comment]
@robjtede Any chance to get a review on this?

**Comment by robjtede** [comment]
done in ac8390ef83090513b2353b3c1bb656108964f4f0 due to lack of maintainer push access to the PR

**Comment by robjtede** [comment]
released dep update in https://crates.io/crates/oas3/0.5.0

**Comment by weiznich** [comment]
Thanks :heart:

**Pull request closed without merging**
